### ISSUE TITLE
Size with superView

### ISSUE THREAD

**Issue by Horray** [noxt/DIDatepicker#14]
The DIDatePicker doesn't re-size together with it's super view

**Comment by yconst** [comment]
This is because autoresizingMask affects the view itself, instead of the child collectionView. To fix this, insert the following:

`_datesCollectionView.autoresizingMask = UIViewAutoresizingFlexibleWidth;`

before `[self addSubview:_datesCollectionView];` , in the `-(UICollectionView *)datesCollectionView;` method implementation.

**Comment by yconst** [comment]
Also remove duplicate from `- (void)setupViews`

**Comment by nbalaji0610** [comment]
Thanks

**Comment by allyrgb** [comment]
That works, thanks, but I can't then get the date cells to automatically resize to align with the screen edges with iPhone 6, like they do with iPhone 5.  However, the demo works ok in this respect.

**Comment by almaskz** [comment]
this can be easily solved my adding DIDatePicker as a subview to UIView that autoresizes correctly. 
@IBOutlet weak var dateView: UIView!               // ui to add DIDatePicker as a subview to it
@IBOutlet weak var scrollView: UIScrollView!    // extra addition to get the scrolling effect when used inside table view
let datePicker = DIDatepicker(frame: self.dateView.frame)
self.scrollView.addSubview(datePicker)              // will need to set contentSize for scroll view manually

**Comment by allyrgb** [comment]
Thank you.

**Comment by noxt** [comment]
Try my new version https://github.com/noxt/ScrollableDatepicker
